server:
    port: 8080

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
            -   id: greeting
                predicates:
                - Path=/greeting
                uri: lb://greeting-ms
    banner:
        location: classpath:banner.txt

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

logging.pattern:
    console: '%d{yyyy-MM.dd HH:mm:ss.SSS XXX} [%-5level] [%-40logger{1}] %msg%n'
