server:
    # random value
    port: 0

spring:
    application:
        name: hello-world-ms

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${random.value}

logging.level:
    com.netflix:
        discovery: WARN
        eureka: WARN

logging.pattern:
    console: '%d{yyyy-MM.dd HH:mm:ss.SSS XXX} [%-5level] [%-40logger{1}] %msg%n'
