server:
    port: 8080

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
            -   id: hello
                predicates:
                - Path=/hello/world
                uri: lb://hello-world-ms

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

logging.pattern:
    console: '%d{yyyy-MM.dd HH:mm:ss.SSS XXX} [%-5level] [%-40logger{1}] %msg%n'
