server:
    port: 8761

spring:
    application:
        name: eureka-server
    banner:
        location: classpath:banner.txt

eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://localhost:8081/eureka

logging.level:
    com.netflix:
        discovery: 'OFF'
        eureka: 'OFF'

logging.pattern:
    console: '%d{yyyy-MM.dd HH:mm:ss.SSS XXX} [%-5level] [%-40logger{1}] %msg%n'
